### ISSUE TITLE
Problems during initial setup

### ISSUE THREAD

**Issue by jh125486** [nviennot/nobrainer#131] opened 2015-03-27 17:40 UTC
I've set everything up (removed ActiveRecord, created nobrainer.rb initializer, unsubclassed models and included NoBrainer::Document).
During `rake nobrainer:setup`, I get this error:

```
rake aborted!
RethinkDB::RqlCompileError: CLIENT ERROR: FUNC variables must be a *literal* array of numbers.
Backtrace:
r.table("users").index_create(:login) {|var_1| var_1.bracket(:login)}
C:in `run'
C:in `sync_indexes'
C:in `sync_indexes'
RethinkDB::RqlCompileError: CLIENT ERROR: FUNC variables must be a *literal* array of numbers.
C:in `run'
C:in `sync_indexes'
C:in `sync_indexes'
Tasks: TOP => nobrainer:setup => nobrainer:sync_indexes_quiet
(See full trace by running task with --trace)
```
This is my seed file (truncated):
```
username = `whoami`.strip.split(/\\/).last
Rails.logger.info "Running user is: #{username}"
user = User.where(login: username).first
user = User.create(login: username) if !user
```
This my user model:
```
class User
  include NoBrainer::Document
  include NoBrainer::Document::Timestamps

  field :login, type: String, index: true
end
```

I'm able to connect to my rethinkdb and see the tables with `NoBrainer.table_list`
I'm sure I'm making some stupid error, but googling didn't show anything and I didn't see any previous issues.
There's a huge backtrace I can post if you need me to.

Any help would be super appreciated.
V/r
Jacob

**Comment by nviennot** [comment] 2015-03-27 17:41
can you share you terminal with me? (you can use tmate.io, and send me an email with the connection string)

**Comment by nviennot** [comment] 2015-03-27 17:54
Well, if you can't, then perhaps a full backtrace would be useful

**Comment by jh125486** [comment] 2015-03-27 17:57
Sorry, I'm on windows here :(

Thanks for the super quick reply btw.
Here's the backtrace:
```
** Invoke nobrainer:setup (first_time)
** Invoke nobrainer:sync_indexes_quiet (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute nobrainer:sync_indexes_quiet
rake aborted!
RethinkDB::RqlCompileError: CLIENT ERROR: FUNC variables must be a *literal* array of numbers.
Backtrace:
r.table("users").index_create(:login) {|var_1| var_1.bracket(:login)}
C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/rethinkdb-1.16.0.1/lib/shim.rb:73:in `rescue in response_to_native'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/rethinkdb-1.16.0.1/lib/shim.rb:60:in `response_to_native'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/rethinkdb-1.16.0.1/lib/net.rb:194:in `run'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/rethinkdb-1.16.0.1/lib/net.rb:42:in `run'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/nobrainer-0.22.0/lib/no_brainer/query_runner/driver.rb:3:in `call'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/nobrainer-0.22.0/lib/no_brainer/query_runner/reconnect.rb:3:in `call'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/nobrainer-0.22.0/lib/no_brainer/query_runner/connection_lock.rb:8:in `block in call'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/nobrainer-0.22.0/lib/no_brainer/query_runner/connection_lock.rb:8:in `synchronize'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/nobrainer-0.22.0/lib/no_brainer/query_runner/connection_lock.rb:8:in `call'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/nobrainer-0.22.0/lib/no_brainer/query_runner/logger.rb:4:in `call'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/nobrainer-0.22.0/lib/no_brainer/query_runner/table_on_demand.rb:3:in `call'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/nobrainer-0.22.0/lib/no_brainer/query_runner/database_on_demand.rb:3:in `call'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/nobrainer-0.22.0/lib/no_brainer/query_runner/missing_index.rb:3:in `call'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/nobrainer-0.22.0/lib/no_brainer/query_runner/write_error.rb:4:in `call'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/nobrainer-0.22.0/lib/no_brainer/query_runner/run_options.rb:33:in `call'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/middleware-0.1.0/lib/middleware/runner.rb:31:in `call'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/middleware-0.1.0/lib/middleware/builder.rb:102:in `call'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/nobrainer-0.22.0/lib/no_brainer/query_runner.rb:24:in `run'
C:in `run'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/nobrainer-0.22.0/lib/no_brainer/document/index/index.rb:60:in `create'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/nobrainer-0.22.0/lib/no_brainer/document/index/synchronizer.rb:18:in `run'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/nobrainer-0.22.0/lib/no_brainer/document/index/synchronizer.rb:54:in `block in sync_indexes'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/nobrainer-0.22.0/lib/no_brainer/document/index/synchronizer.rb:54:in `each'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/nobrainer-0.22.0/lib/no_brainer/document/index/synchronizer.rb:54:in `sync_indexes'
C:in `sync_indexes'
C:in `sync_indexes'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/nobrainer-0.22.0/lib/no_brainer/railtie/database.rake:13:in `block (2 levels) in <top (required)>'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:240:in `call'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:240:in `block in execute'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `each'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:201:in `block in invoke_prerequisites'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:199:in `each'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:199:in `invoke_prerequisites'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:178:in `block in invoke_with_call_chain'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `each'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `block in top_level'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:78:in `block in run'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
C:/RailsInstaller/Ruby2.1.0/bin/rake:23:in `load'
C:/RailsInstaller/Ruby2.1.0/bin/rake:23:in `<main>'
RethinkDB::RqlCompileError: CLIENT ERROR: FUNC variables must be a *literal* array of numbers.
C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/rethinkdb-1.16.0.1/lib/shim.rb:68:in `response_to_native'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/rethinkdb-1.16.0.1/lib/net.rb:194:in `run'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/rethinkdb-1.16.0.1/lib/net.rb:42:in `run'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/nobrainer-0.22.0/lib/no_brainer/query_runner/driver.rb:3:in `call'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/nobrainer-0.22.0/lib/no_brainer/query_runner/reconnect.rb:3:in `call'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/nobrainer-0.22.0/lib/no_brainer/query_runner/connection_lock.rb:8:in `block in call'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/nobrainer-0.22.0/lib/no_brainer/query_runner/connection_lock.rb:8:in `synchronize'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/nobrainer-0.22.0/lib/no_brainer/query_runner/connection_lock.rb:8:in `call'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/nobrainer-0.22.0/lib/no_brainer/query_runner/logger.rb:4:in `call'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/nobrainer-0.22.0/lib/no_brainer/query_runner/table_on_demand.rb:3:in `call'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/nobrainer-0.22.0/lib/no_brainer/query_runner/database_on_demand.rb:3:in `call'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/nobrainer-0.22.0/lib/no_brainer/query_runner/missing_index.rb:3:in `call'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/nobrainer-0.22.0/lib/no_brainer/query_runner/write_error.rb:4:in `call'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/nobrainer-0.22.0/lib/no_brainer/query_runner/run_options.rb:33:in `call'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/middleware-0.1.0/lib/middleware/runner.rb:31:in `call'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/middleware-0.1.0/lib/middleware/builder.rb:102:in `call'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/nobrainer-0.22.0/lib/no_brainer/query_runner.rb:24:in `run'
C:in `run'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/nobrainer-0.22.0/lib/no_brainer/document/index/index.rb:60:in `create'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/nobrainer-0.22.0/lib/no_brainer/document/index/synchronizer.rb:18:in `run'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/nobrainer-0.22.0/lib/no_brainer/document/index/synchronizer.rb:54:in `block in sync_indexes'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/nobrainer-0.22.0/lib/no_brainer/document/index/synchronizer.rb:54:in `each'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/nobrainer-0.22.0/lib/no_brainer/document/index/synchronizer.rb:54:in `sync_indexes'
C:in `sync_indexes'
C:in `sync_indexes'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/nobrainer-0.22.0/lib/no_brainer/railtie/database.rake:13:in `block (2 levels) in <top (required)>'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:240:in `call'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:240:in `block in execute'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `each'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:201:in `block in invoke_prerequisites'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:199:in `each'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:199:in `invoke_prerequisites'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:178:in `block in invoke_with_call_chain'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `each'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `block in top_level'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:78:in `block in run'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
C:/RailsInstaller/Ruby2.1.0/bin/rake:23:in `load'
C:/RailsInstaller/Ruby2.1.0/bin/rake:23:in `<main>'
```

**Comment by nviennot** [comment] 2015-03-27 18:04
what version of rethinkdb (the server) are you running?

(from what I'm seeing, it's the server that is throwing up this error.)
Maybe it's a windows related bug, I'm not sure.

**Comment by jh125486** [comment] 2015-03-27 18:06
Latest version I believe, dashboard shows RethinkDB 1.16.2-1
I'll push my branch to our linux box and see if the error is still there.

**Comment by jh125486** [comment] 2015-03-27 18:20
Just tested the linux box, same error on linux box when it goes to index_create(:login)

**Comment by nviennot** [comment] 2015-03-27 18:21
share you terminal then :)
because I can't reproduce locally, even with the versions that you are running with.

**Comment by jh125486** [comment] 2015-03-27 18:59
`tmate -S /tmp/tmate.sock wait tmate-ready` never returns from establishing an ssh tunnel, so I'm guessing our firewalls are dropping the connections.
Thanks for your help though.  I'm going to try and create a blank app from scratch and see if I can repeat the error.

**Comment by nviennot** [comment] 2015-03-27 19:01
if you just lunch `tmate`, it should quickly tell you a connection string at the bottom.
It should at least tell you that the connection times out if there's a problem.
If you can't shared the terminal, I'd be happy to see a self contained test.

Btw, can you run the test suite of nobrainer?
```
git clone https://github.com/nviennot/nobrainer.git
cd nobrainer
bundle install
bundle exec rspec
```

**Comment by jh125486** [comment] 2015-03-27 19:18
0 failures with rpsec tests, and the barebones basic app with one model is working.
I'll slowing add in the rest of the branch and see where things break.  
Thanks again for your help.

**Comment by nviennot** [comment] 2015-03-27 19:18
thank you!

**Comment by jh125486** [comment] 2015-03-29 17:57
Looks like all the trouble got reduced to the gem `oj_mimic_json`
I'm guessing it does some funky monkey patching of JSON.

**Comment by nviennot** [comment] 2015-03-29 19:09
I made a quick patch that potentially would avoid the issue: https://github.com/nviennot/nobrainer/commit/2fb3eaab4ea7fe3d3958487cada18dd3796b4654

If you could try this in your gemfile: `gem "nobrainer", github: "nviennot/nobrainer", branch: "json"`
with the `oj_mimic_json` gem loaded in, I'd be happy to see if the problem still manifests.

Thank you :)

**Comment by jh125486** [comment] 2015-03-29 20:17
With json branch, same errors reported: `RethinkDB::RqlCompileError: CLIENT ERROR: FUNC variables must be a *literal* array of numbers.`

**Comment by nviennot** [comment] 2015-04-12 21:46
I'm closing this issue because this is not a nobrainer issue, but a compat issue between oj_minic and the rethinkdb gem.

**Closed by nviennot** 2015-04-12 21:46 UTC
